---
- name: Add mesosphere repo
  yum: name=http://repos.mesosphere.io/el/6/noarch/RPMS/mesosphere-el-repo-6-2.noarch.rpm state=present

- name: Install Chronos
  yum: name=chronos-{{chronos_version}} state=present